#!/bin/bash

# Открываем терминал
gnometerminal &
sleep 2

# Отключаем встроеный eDP-1
xrandr --output eDP-1 --off

# Получаем список всех подключенных мониторов
connected_monitors="$(xrandr | grep -w 'connected' | awk '{print $1}')"
primary_monitor=""

# Проверяем каждый подключенный монитор
for monitor in $connected_monitors; do
    # Получаем информацию о мониторе
    monitor_info="$(xrandr --query | grep -w $monitor)"
    monitor_status="$(echo $monitor_info | awk '{print $2}')"
    
    # Если статус монитора "connected", делаем его главным
    if [ "$monitor_status" = "connected" ]; then
        xrandr --output $monitor --primary
        primary_monitor="$monitor"
    fi
done
