#!/bin/bash
  ##Получение id
  DEVICE_ID=$(lspci -v | grep "VGA compatible controller" -A 1 | grep"Device" | awk'{print $3}
  FILE_ID=$(cat /etc/default/grub)
  if[${DEVICE_ID}!=${FILE_ID}]
    ##Вставка id
    ##sudo sed -i "s/^GRUB_CMDLINE_LINUX_DEFAULT=.*           -???
    sudo sed -i '4iGRUB_CMDLINE_LINUX_DEFAULT=.i915.force_probe={} i915.modeset=1'
    ##/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash pci=ids.
    ##$device_id\"/" /etc/default/grub
    ##Обновление конфигурации
    update-grub
    ##Раскомментировать для отладки \/
    ##sudo nano /etc/default/grub
  else
    fi
